target 'HydroSwede' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HydroSwede

  pod 'SkyFloatingLabelTextField', '~> 3.2'
  pod 'PWSwitch'

end
